name: Run tests

on:
  push:
    branches:
      - 'test'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Set secrets in .env file
        run: |
          echo "${{ secrets.SHERPA["SLACK_SIGNING_SECRET"] }}" 
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          cd src
          pip install numpy==1.25.2
          poetry install
          echo "am IN HERE"
          poetry run pytest --cov=sherpa_ai .

     
