name: Run tests

on:
  push:
    branches:
      - 'test'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          cd src
          pip install numpy==1.25.2
          echo "am IN HERE"
          poetry install

      - name: Run pytest
        run: |
          echo "am IN HERE"
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry run pytest --cov=myapp src/tests/
          echo "am IN HERE"
        env:
          FLASK_ENV: debug

