name: Run tests

on:
  push:
    branches:
      - 'test'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          cd src
          echo "am IN HERE"
          pip install numpy==1.25.2
          poetry install

      - name: Run pytest
        run: poetry run pytest --cov=myapp tests/
        env:
          FLASK_ENV: testing

